# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b217238dea6468a4148c29317b8cc16d2d5d66b18e2ccda4c237c4f6ea7aedc19aad0b200fb318fff1ce342f08d17cacc241b1655f3ebb9ff4312ac7772b4aee

test:
  secret_key_base: b217238dea6468a4148c29317b8cc16d2d5d66b18e2ccda4c237c4f6ea7aedc19aad0b200fb318fff1ce342f08d17cacc241b1655f3ebb9ff4312ac7772b4aee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
